### PR TITLE
Multi-RHS solvers (incl. multigrid) from QUDA.

### PR DESCRIPTION
**Pull request by bjoo**
Features for using Multigrid with MRHS - both for Subspace creation and for Solves. Requires an update of QUDA (develop) version eead44e1595ef473ff559a0b8556d0ace9a9eb6e or later (post merge of QUDA feature/mrhs-solvers branch)

### CODE REVIEW

**Comment by fwinter** [comment]
Hey Balint! This works fine for me. Both, the non-QUDA and QUDA route tested.

**Comment by eromero-vlc** [comment]
I have been testing it with qdp-jit and rocm 6.1 and works fine!

**Comment by bjoo** [comment]
[like]  Balint Joo reacted to your message:
________________________________

**Comment by bjoo** [comment]
[0]     Balint Joo reacted to your message:
________________________________

**Pull request merged**
